# START_MODULE_CONTRACT
#   PURPOSE: Generate tokens.css from tokens.json and verify contrast pairs.
#   SCOPE: Design tokens only.
#   DEPENDS: none
#   LINKS: M-PORTAL-SOURCE, V-M-PORTAL-SOURCE
# END_MODULE_CONTRACT
#
# START_MODULE_MAP
#   ROOT - module-internal helper or constant
#   PAIRS - module-internal helper or constant
#   luminance - module-internal helper or constant
#   contrast - module-internal helper or constant
#   css_block - module-internal helper or constant
#   load_tokens - module-internal helper or constant
#   tokens_css - module-internal helper or constant
#   contrast_results - contrast check for every theme
#   write_tokens - write tokens.css and return contrast results
# END_MODULE_MAP
"""Generate tokens.css from tokens.json and verify contrast pairs (adapted from the EA portal build)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

PAIRS = [('text', 'surface', 4.5), ('text', 'canvas', 4.5), ('text', 'surface-selected', 4.5),
         ('text', 'surface-subtle', 4.5), ('text-muted', 'surface', 4.5), ('text-muted', 'canvas', 4.5),
         ('link', 'surface', 4.5), ('link', 'surface-selected', 4.5), ('on-action', 'action', 4.5),
         ('on-action', 'action-hover', 4.5), ('focus', 'surface', 3), ('focus', 'canvas', 3),
         ('border-control', 'surface', 3)] + [(s, s + '-bg', 4.5) for s in ('success', 'warning', 'error', 'info')]


def luminance(value):
    values = [int(value[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [v / 12.92 if v <= .04045 else ((v + .055) / 1.055) ** 2.4 for v in values]
    return sum(v * k for v, k in zip(linear, (.2126, .7152, .0722)))


def contrast(a, b):
    low, high = sorted((luminance(a), luminance(b)))
    return (high + .05) / (low + .05)


def css_block(selector, values):
    return selector + ' {\n' + ''.join(f'  --{k}: {v};\n' for k, v in values.items()) + '}\n'


def load_tokens():
    return json.loads((ROOT / 'tokens/tokens.json').read_text(encoding='utf-8'))


def tokens_css(tokens):
    css = '/* Generated by tools/build.py. Edit tokens.json. */\n' + css_block(':root', tokens['global'])
    for theme, values in tokens['themes'].items():
        css += css_block(':root' if theme == 'light' else '[data-theme="dark"]', values)
    css += ':root { color-scheme: light; }\n[data-theme="dark"] { color-scheme: dark; }\n'
    return css


def contrast_results(tokens):
    results = []
    for theme, values in tokens['themes'].items():
        for fg, bg, target in PAIRS:
            ratio = contrast(values[fg], values[bg])
            results.append({'theme': theme, 'foreground': fg, 'background': bg,
                            'ratio': round(ratio, 2), 'target': target, 'pass': ratio >= target})
    return results


def write_tokens():
    tokens = load_tokens()
    (ROOT / 'tokens/tokens.css').write_text(tokens_css(tokens), encoding='utf-8')
    return contrast_results(tokens)
